"""initial schema

Revision ID: aa9be6b2875f
Revises: 
Create Date: 2026-04-15 08:47:19.987343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9be6b2875f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pg_trgm for fuzzy club name search
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pipeline_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_ingestion_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('source_commit_hash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('position_group', sa.String(length=3), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('transfermarkt_id', sa.String(length=50), nullable=True),
    sa.Column('transfermarkt_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfermarkt_id')
    )
    op.create_index(op.f('ix_players_date_of_birth'), 'players', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_players_position_group'), 'players', ['position_group'], unique=False)
    op.create_table('country_transfer_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_country_id', sa.Integer(), nullable=False),
    sa.Column('to_country_id', sa.Integer(), nullable=False),
    sa.Column('transfer_window', sa.String(length=20), nullable=False),
    sa.Column('total_fee_eur', sa.BigInteger(), nullable=False),
    sa.Column('transfer_count', sa.Integer(), nullable=False),
    sa.Column('loan_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_country_flow', 'country_transfer_flows', ['from_country_id', 'to_country_id', 'transfer_window'], unique=True)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('transfermarkt_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfermarkt_id')
    )
    op.create_table('player_valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('valuation_eur', sa.BigInteger(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_valuations_player_id'), 'player_valuations', ['player_id'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('current_league_id', sa.Integer(), nullable=True),
    sa.Column('transfermarkt_id', sa.String(length=50), nullable=True),
    sa.Column('transfermarkt_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_league_id'], ['leagues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfermarkt_id')
    )
    op.create_index(op.f('ix_clubs_country_id'), 'clubs', ['country_id'], unique=False)
    op.create_index(op.f('ix_clubs_current_league_id'), 'clubs', ['current_league_id'], unique=False)
    op.create_table('club_transfer_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('transfer_window', sa.String(length=20), nullable=False),
    sa.Column('total_spent_eur', sa.BigInteger(), nullable=False),
    sa.Column('total_received_eur', sa.BigInteger(), nullable=False),
    sa.Column('players_bought', sa.Integer(), nullable=False),
    sa.Column('players_sold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_club_summary', 'club_transfer_summaries', ['club_id', 'transfer_window'], unique=True)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('from_club_id', sa.Integer(), nullable=False),
    sa.Column('to_club_id', sa.Integer(), nullable=False),
    sa.Column('fee_eur', sa.BigInteger(), nullable=True),
    sa.Column('fee_is_loan', sa.Boolean(), nullable=False),
    sa.Column('transfer_window', sa.String(length=20), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('season', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['from_club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_from_club_id'), 'transfers', ['from_club_id'], unique=False)
    op.create_index('ix_transfers_from_to_window', 'transfers', ['from_club_id', 'to_club_id', 'transfer_window'], unique=False)
    op.create_index(op.f('ix_transfers_player_id'), 'transfers', ['player_id'], unique=False)
    op.create_index(op.f('ix_transfers_to_club_id'), 'transfers', ['to_club_id'], unique=False)
    op.create_index('ix_transfers_window', 'transfers', ['transfer_window'], unique=False)
    op.create_index('uq_transfers_natural_key', 'transfers', ['player_id', 'transfer_date', 'from_club_id', 'to_club_id'], unique=True)
    # ### end Alembic commands ###

    # GIN trigram index for club name search
    op.execute(
        "CREATE INDEX ix_clubs_name_trgm ON clubs USING GIN (name gin_trgm_ops)"
    )

    # Seed countries
    countries_table = sa.table(
        'countries',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('iso_code', sa.String),
        sa.column('latitude', sa.Numeric),
        sa.column('longitude', sa.Numeric),
        sa.column('in_scope', sa.Boolean),
    )
    op.bulk_insert(countries_table, [
        {"id": 1,  "name": "England",     "iso_code": "ENG", "latitude": 52.3555,  "longitude": -1.1743,  "in_scope": True},
        {"id": 2,  "name": "Scotland",    "iso_code": "SCO", "latitude": 56.4907,  "longitude": -4.2026,  "in_scope": True},
        {"id": 3,  "name": "Spain",       "iso_code": "ESP", "latitude": 40.4637,  "longitude": -3.7492,  "in_scope": True},
        {"id": 4,  "name": "Germany",     "iso_code": "DEU", "latitude": 51.1657,  "longitude": 10.4515,  "in_scope": True},
        {"id": 5,  "name": "Italy",       "iso_code": "ITA", "latitude": 41.8719,  "longitude": 12.5674,  "in_scope": True},
        {"id": 6,  "name": "France",      "iso_code": "FRA", "latitude": 46.2276,  "longitude": 2.2137,   "in_scope": True},
        {"id": 7,  "name": "Portugal",    "iso_code": "PRT", "latitude": 39.3999,  "longitude": -8.2245,  "in_scope": True},
        {"id": 8,  "name": "Netherlands", "iso_code": "NLD", "latitude": 52.1326,  "longitude": 5.2913,   "in_scope": True},
        {"id": 9,  "name": "Belgium",     "iso_code": "BEL", "latitude": 50.5039,  "longitude": 4.4699,   "in_scope": True},
        {"id": 10, "name": "Turkey",      "iso_code": "TUR", "latitude": 38.9637,  "longitude": 35.2433,  "in_scope": True},
        {"id": 11, "name": "Argentina",   "iso_code": "ARG", "latitude": -38.4161, "longitude": -63.6167, "in_scope": True},
        {"id": 12, "name": "Brazil",      "iso_code": "BRA", "latitude": -14.2350, "longitude": -51.9253, "in_scope": True},
        {"id": 13, "name": "Other",       "iso_code": "OTH", "latitude": 0.0,      "longitude": 0.0,      "in_scope": False},
    ])

    # Seed leagues (transfermarkt_id left NULL — populated by pipeline)
    leagues_table = sa.table(
        'leagues',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('country_id', sa.Integer),
        sa.column('tier', sa.Integer),
    )
    op.bulk_insert(leagues_table, [
        {"id": 1,  "name": "Premier League",    "country_id": 1,  "tier": 1},
        {"id": 2,  "name": "Championship",      "country_id": 1,  "tier": 2},
        {"id": 3,  "name": "La Liga",           "country_id": 3,  "tier": 1},
        {"id": 4,  "name": "Segunda División",  "country_id": 3,  "tier": 2},
        {"id": 5,  "name": "Bundesliga",        "country_id": 4,  "tier": 1},
        {"id": 6,  "name": "2. Bundesliga",     "country_id": 4,  "tier": 2},
        {"id": 7,  "name": "Serie A",           "country_id": 5,  "tier": 1},
        {"id": 8,  "name": "Ligue 1",           "country_id": 6,  "tier": 1},
        {"id": 9,  "name": "Primeira Liga",     "country_id": 7,  "tier": 1},
        {"id": 10, "name": "Eredivisie",        "country_id": 8,  "tier": 1},
        {"id": 11, "name": "Pro League",        "country_id": 9,  "tier": 1},
        {"id": 12, "name": "Süper Lig",         "country_id": 10, "tier": 1},
        {"id": 13, "name": "Premiership",       "country_id": 2,  "tier": 1},
        {"id": 14, "name": "Primera División",  "country_id": 11, "tier": 1},
        {"id": 15, "name": "Série A",           "country_id": 12, "tier": 1},
    ])

    # Reset sequences to start after seeded IDs
    op.execute("SELECT setval('countries_id_seq', 13)")
    op.execute("SELECT setval('leagues_id_seq', 15)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_transfers_natural_key', table_name='transfers')
    op.drop_index('ix_transfers_window', table_name='transfers')
    op.drop_index(op.f('ix_transfers_to_club_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_player_id'), table_name='transfers')
    op.drop_index('ix_transfers_from_to_window', table_name='transfers')
    op.drop_index(op.f('ix_transfers_from_club_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index('uq_club_summary', table_name='club_transfer_summaries')
    op.drop_table('club_transfer_summaries')
    op.drop_index(op.f('ix_clubs_current_league_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_country_id'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_player_valuations_player_id'), table_name='player_valuations')
    op.drop_table('player_valuations')
    op.drop_table('leagues')
    op.drop_index('uq_country_flow', table_name='country_transfer_flows')
    op.drop_table('country_transfer_flows')
    op.drop_index(op.f('ix_players_position_group'), table_name='players')
    op.drop_index(op.f('ix_players_date_of_birth'), table_name='players')
    op.drop_table('players')
    op.drop_table('pipeline_metadata')
    op.drop_table('countries')
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
